[package]
name = "gif2json"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0.24.3"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
